# Flyway Configuration
spring.flyway.enabled=false

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# Simulador Configuration
publisher.simulador.enabled=false
publisher.simulador.criar-cobranca=false
