# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=pix_received_publisher

# JPA Configuration
spring.jpa.properties.hibernate.default_schema=pix_received_publisher
spring.jpa.properties.hibernate.schema_management_tool=org.hibernate.tool.schema.internal.HibernateSchemaManagementTool

# Simulador Configuration
publisher.simulador.enabled=false
publisher.simulador.criar-cobranca=false
