# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.schemas=pix_received_publisher
spring.flyway.locations=classpath:db/migration

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate

# Simulador Configuration
publisher.simulador.enabled=false
publisher.simulador.criar-cobranca=false
